### ISSUE TITLE
migrations are not working?

### ISSUE THREAD

**Issue by gowtham-sai** [jwo/ActiveRecord-Without-Rails#2]
I'm using Postgres database. And any migrations are not working. Can you try and check whether it is working for you?

**Comment by jwo** [comment]
@gowtham-sai I just pushed an update that required an upgrade in the Gemfile and the format of the migrations to work with Rails 5+ (1d3ea9f). When I did that, I was able to migrate the database and run `ruby ar-no-rails.rb` to connect.

Will you check and see if that works for you? Otherwise, make sure to change the db and username in config/database.yml to your setup.

**Comment by gowtham-sai** [comment]
I'm working on AR 4.2. I guess the issue is because of the location of [migrations files](https://github.com/jwo/ActiveRecord-Without-Rails/blob/1d3ea9fce10a19c69f1625744088fcf7d2749d68/Rakefile#L14). You need to specify the outer folder which contains the migrations.  

```ruby 
    # lib/db/migrations/23432423_name_migrate.rb -> Actual file location. 
    ActiveRecord::Migrator.migrate("lib/db/")
```

**Comment by jwo** [comment]
@gowtham-sai thanks for the update! ActiveRecord definitely expects the migrations to exist in `db/migrations` like in a rails app. Going to update the README to mention this to help people in future.
